### ISSUE TITLE
Needs metadata

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Dynamic-Fuel-System#1]

**Comment by aruzicka555** [comment]
Pull request submitted, ready for testing

**Comment by bmarron18** [comment]
See [LANDIS-II-Foundation/Extension-Dynamic-Fuel]

First round QAQC a no-go:
Internal error occurred within the program: Object reference not set to an instance of an object.

Stack trace: at Landis.Library.Metadata.DataTableExtensions.SetColumns[T](DataTable tbl)
at Landis.Library.Metadata.MetadataTable`1..ctor(String filePath)
at Landis.Extension.DynamicFire.MetadataHandler.InitializeMetadata(String mapNameTemplate, String eventLogName, String summaryLogName)
at Landis.Extension.DynamicFire.PlugIn.Initialize()
at Landis.Model.InitExtensions(ExtensionMain[] extensions)
at Landis.Model.Run(String scenarioPath, IUserInterface ui)
at Landis.App.Main(String[] args)
